{{- if .Values.rbacEnabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.service.namespace }}
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - create
    - get
    - list
    - delete
{{- end -}}
